# -*- coding: utf-8 -*-
"""Program 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k7mIFl4lB3itx_VA_a0kmlgiwWVQWMrM
"""

import numpy as np

def jenis_cluster(U):

    A = np.array([-1, 4, 2])
    B = np.array([5, -2, 7])
    C = np.array([2, 3, 5])

    def jarak(p, q):
        return np.sqrt(np.sum((p - q)**2))

    U = np.array(U)

    dA = jarak(U, A)
    dB = jarak(U, B)
    dC = jarak(U, C)

    print("Jarak U ke A:", dA)
    print("Jarak U ke B:", dB)
    print("Jarak U ke C:", dC)

    if dA < dB and dA < dC:
        return "Cluster A"

    elif dB < dA and dB < dC:
        return "Cluster B"

    elif dC < dA and dC < dB:
        return "Cluster C"

    elif dA == dB and dA < dC:
        return "Perbatasan cluster A dan cluster B"

    elif dA == dC and dA < dB:
        return "Perbatasan cluster A dan cluster C"

    elif dB == dC and dB < dA:
        return "Perbatasan Cluster B dan Cluster C"

    else:
        return "Perbatasan Cluster A, B, dan C"


# Kondisi 1
hasil = jenis_cluster([2, 3, 3])
print("Titik U masuk ke dalam:", hasil, "\n")

# Kondisi 2
hasil = jenis_cluster([2, -2, 5])
print("Titik U masuk ke dalam:", hasil, "\n")

# Kondisi 3
hasil = jenis_cluster([1, 1, 2])
print("Titik U masuk ke dalam:", hasil, "\n")
