# -*- coding: utf-8 -*-
"""PROGRAM 6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ex4W720UrInhdTwN3x-iHgdDx1uq6R1O
"""

import numpy as np

def interval_konfidensi(p_hat, alpha, n):

    # Validasi nilai proporsi
    if p_hat < 0 or p_hat > 1:
        print("Error: Proporsi harus bernilai antara 0 dan 1.")
        return

    # Menentukan nilai z berdasarkan alpha
    if alpha == 0.10:
        z = 1.645

    elif alpha == 0.05:
        z = 1.96

    else:
        print("Error: Alpha harus 0.05 atau 0.10.")
        return

    # Menghitung margin of error
    margin = z * np.sqrt(p_hat * (1 - p_hat) / n)

    # Menghitung batas interval
    batas_bawah = p_hat - margin
    batas_atas = p_hat + margin

    # Menampilkan hasil
    print(f"Interval Konfidensi ({(1-alpha)*100:.0f}%):")
    print(f"{batas_bawah:.4f} < p < {batas_atas:.4f}")


#Skenario 1
interval_konfidensi(0.6, 0.05, 1000)

#Skenario 2
interval_konfidensi(0.8, 0.10, 500)

#Skenario 3
interval_konfidensi(2, 0.1, 800)

#Skenario 4
interval_konfidensi(0.5, 0.9, 3000)