# -*- coding: utf-8 -*-
"""program 6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14UuxfXOx6YRY2Mwf1jSi-WX1vszoAF1a
"""

#PROGRAM 6
#skenario 1
p_hat = float(input("Masukkan proporsi sampel (p_hat): "))
alpha = float(input("Masukkan tingkat kepercayaan alpha (0.05 atau 0.10): "))
if p_hat < 0 or p_hat > 1:
    print("Error: Proporsi harus bernilai antara 0 dan 1.")
else:
    if alpha == 0.10:
        z = 1.645
    elif alpha == 0.05:
        z = 1.96
    else:
        print("Error: Alpha harus 0.05 atau 0.10.")
        exit()
    n = int(input("Masukkan ukuran sampel (n): "))
    margin = z * ((p_hat * (1 - p_hat) / n) ** 0.5)
    batas_bawah = p_hat - margin
    batas_atas  = p_hat + margin
    print(f"\nInterval Konfidensi ({(1-alpha)*100:.0f}%):")
    print(f"{batas_bawah:.4f} < p < {batas_atas:.4f}")

#skenario 2
p_hat = float(input("Masukkan proporsi sampel (p_hat): "))
alpha = float(input("Masukkan tingkat kepercayaan alpha (0.05 atau 0.10): "))
if p_hat < 0 or p_hat > 1:
    print("Error: Proporsi harus bernilai antara 0 dan 1.")
else:
    if alpha == 0.10:
        z = 1.645
    elif alpha == 0.05:
        z = 1.96
    else:
        print("Error: Alpha harus 0.05 atau 0.10.")
        exit()
    n = int(input("Masukkan ukuran sampel (n): "))
    margin = z * ((p_hat * (1 - p_hat) / n) ** 0.5)
    batas_bawah = p_hat - margin
    batas_atas  = p_hat + margin
    print(f"\nInterval Konfidensi ({(1-alpha)*100:.0f}%):")
    print(f"{batas_bawah:.4f} < p < {batas_atas:.4f}")

#skenario 3
p_hat = float(input("Masukkan proporsi sampel (p_hat): "))
alpha = float(input("Masukkan tingkat kepercayaan alpha (0.05 atau 0.10): "))
if p_hat < 0 or p_hat > 1:
    print("Error: Proporsi harus bernilai antara 0 dan 1.")
else:
    if alpha == 0.10:
        z = 1.645
    elif alpha == 0.05:
        z = 1.96
    else:
        print("Error: Alpha harus 0.05 atau 0.10.")
        exit()
    n = int(input("Masukkan ukuran sampel (n): "))
    margin = z * ((p_hat * (1 - p_hat) / n) ** 0.5)
    batas_bawah = p_hat - margin
    batas_atas  = p_hat + margin
    print(f"\nInterval Konfidensi ({(1-alpha)*100:.0f}%):")
    print(f"{batas_bawah:.4f} < p < {batas_atas:.4f}")