# -*- coding: utf-8 -*-
"""program 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CZIIsDXBjc9q3J2fxr5xHJ4jLsj4frAx
"""

#PROGRAM 5
#skenario 1
import math
# Pusat cluster
A = (2, 1, 3)
B = (1, -4, 6)
C = (-2, 3, -2)
# Input titik U
u = input("Masukkan koordinat titik U (x1 x2 x3 dipisah spasi): ")
x1, x2, x3 = map(float, u.split())
U = (x1, x2, x3)
def jarak(p, q):
    return math.sqrt((p[0]-q[0])**2 + (p[1]-q[1])**2 + (p[2]-q[2])**2)
dA = jarak(U, A)
dB = jarak(U, B)
dC = jarak(U, C)
print(f"Jarak ke A: {dA:.4f}")
print(f"Jarak ke B: {dB:.4f}")
print(f"Jarak ke C: {dC:.4f}")
if dA <= dB and dA <= dC:
    print("Titik U tergolong Cluster A")
elif dB <= dA and dB <= dC:
    print("Titik U tergolong Cluster B")
else:
    print("Titik U tergolong Cluster C")

#skenario 2
import math
# Pusat cluster
A = (2, 1, 3)
B = (1, -4, 6)
C = (-2, 3, -2)
# Input titik U
u = input("Masukkan koordinat titik U (x1 x2 x3 dipisah spasi): ")
x1, x2, x3 = map(float, u.split())
U = (x1, x2, x3)
def jarak(p, q):
    return math.sqrt((p[0]-q[0])**2 + (p[1]-q[1])**2 + (p[2]-q[2])**2)
dA = jarak(U, A)
dB = jarak(U, B)
dC = jarak(U, C)
print(f"Jarak ke A: {dA:.4f}")
print(f"Jarak ke B: {dB:.4f}")
print(f"Jarak ke C: {dC:.4f}")
if dA <= dB and dA <= dC:
    print("Titik U tergolong Cluster A")
elif dB <= dA and dB <= dC:
    print("Titik U tergolong Cluster B")
else:
    print("Titik U tergolong Cluster C")

#skenario 3
import math
# Pusat cluster
A = (2, 1, 3)
B = (1, -4, 6)
C = (-2, 3, -2)
# Input titik U
u = input("Masukkan koordinat titik U (x1 x2 x3 dipisah spasi): ")
x1, x2, x3 = map(float, u.split())
U = (x1, x2, x3)
def jarak(p, q):
    return math.sqrt((p[0]-q[0])**2 + (p[1]-q[1])**2 + (p[2]-q[2])**2)
dA = jarak(U, A)
dB = jarak(U, B)
dC = jarak(U, C)
print(f"Jarak ke A: {dA:.4f}")
print(f"Jarak ke B: {dB:.4f}")
print(f"Jarak ke C: {dC:.4f}")
if dA <= dB and dA <= dC:
    print("Titik U tergolong Cluster A")
elif dB <= dA and dB <= dC:
    print("Titik U tergolong Cluster B")
else:
    print("Titik U tergolong Cluster C")