# -*- coding: utf-8 -*-
"""Program 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Xjy49nlSnhixfs3TQ4Y9xBtUewgWJ1Z
"""

#PROGRAM 4
#skenario 1
nip = input("Masukkan NIP ASN (18 digit):")
tahun = nip[0:4]
bulan_angka = int(nip[4:6])
tanggal = nip[6:8]
bulan_dict = {
1: "Januari", 2: "Februari", 3: "Maret", 4: "April",
5: "Mei", 6: "Juni", 7: "Juli", 8: "Agustus",
9: "September", 10: "Oktober", 11: "November", 12: "Desember"
}
if bulan_angka in bulan_dict:
 nama_bulan = bulan_dict[bulan_angka]
else:
 nama_bulan = "Tidak diketahui"
print(f"Tanggal lahir ASN: {tanggal} {nama_bulan} {tahun}")

#skenario 2
nip = input("Masukkan NIP ASN (18 digit):")
tahun = nip[0:4]
bulan_angka = int(nip[4:6])
tanggal = nip[6:8]
bulan_dict = {
1: "Januari", 2: "Februari", 3: "Maret", 4: "April",
5: "Mei", 6: "Juni", 7: "Juli", 8: "Agustus",
9: "September", 10: "Oktober", 11: "November", 12: "Desember"
}
if bulan_angka in bulan_dict:
 nama_bulan = bulan_dict[bulan_angka]
else:
 nama_bulan = "Tidak diketahui"
print(f"Tanggal lahir ASN: {tanggal} {nama_bulan} {tahun}")

#skenario 3
nip = input("Masukkan NIP ASN (18 digit):")
tahun = nip[0:4]
bulan_angka = int(nip[4:6])
tanggal = nip[6:8]
bulan_dict = {
1: "Januari", 2: "Februari", 3: "Maret", 4: "April",
5: "Mei", 6: "Juni", 7: "Juli", 8: "Agustus",
9: "September", 10: "Oktober", 11: "November", 12: "Desember"
}
if bulan_angka in bulan_dict:
 nama_bulan = bulan_dict[bulan_angka]
else:
 nama_bulan = "Tidak diketahui"
print(f"Tanggal lahir ASN: {tanggal} {nama_bulan} {tahun}")