# -*- coding: utf-8 -*-
"""program 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J0DPKHQ4Pyv_hhzbwDI0ebXlJwCdd3-z
"""

#PROGRAM 1
#skenario 1
teks = """Media sosial atau disebut juga dengan jejaring sosial,
seperti
Facebook, Twitter, Instagram, dan masih banyak lagi ternyata tidak
hanya
digunakan sebagai tempat berkumpul atau berbagi di dunia maya. Namun,
media
sosial kini juga bisa dimanfaatkan sebagai media untuk mengembangkan
sebuah
bisnis. Saat ini telah banyak para pengusaha yang beralih ke media
sosial dalam
memasarkan produk mereka baik barang ataupun jasa. Beralihnya para
pelaku
bisnis ke media ini dikarenakan jejaring sosial memiliki manfaat yang
sangat
banyak bagi usaha bisnis. Berikut ini adalah alasan mengapa jejaring
sosial
bisa menjadi alat promosi yang paling efektif."""
jumlah_kalimat = teks.count('.')
jumlah_kata = len(teks.split())
print(f"Teks tersebut memuat {jumlah_kalimat} kalimat dan {jumlah_kata} kata.")

#skenario 2
teks = "Badan Pusat Statistik (BPS) menginformasikan bahwa jumlah orang miskin di Indonesia diperkirakan mencapai hampir 25 juta orang ditahun 2019. Secara ekonomi, yang dimaksud orang miskin adalah orang dengan kesulitan untuk memenuhi kebutuhan hidup."
jumlah_kalimat = teks.count('.')
jumlah_kata = len(teks.split())
print(f"Teks tersebut memuat {jumlah_kalimat} kalimat dan {jumlah_kata} kata.")

#skenario 3
teks = "Jatuh cinta adalah perasaan yang muncul ketika seseorang mulai merasa nyaman, kagum, dan memiliki ketertarikan yang mendalam kepada orang lain. Perasaan ini sering menghadirkan kebahagiaan sederhana, seperti senyum yang muncul tanpa alasan, rasa rindu saat berjauhan, dan keinginan untuk selalu melihat orang yang dicintai bahagia. Meski terkadang membawa rasa cemas dan keraguan, jatuh cinta tetap menjadi salah satu pengalaman indah yang membuat hidup terasa lebih berwarna dan bermakna."
jumlah_kalimat = teks.count('.')
jumlah_kata = len(teks.split())
print(f"Teks tersebut memuat {jumlah_kalimat} kalimat dan {jumlah_kata} kata.")